<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventParking.Models\EventParking.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Configurations\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Migrations\" />
    <Folder Include="Seed\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
