<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventParking.Api\EventParking.Api.csproj" />
    <ProjectReference Include="..\EventParking.Business\EventParking.Business.csproj" />
    <ProjectReference Include="..\EventParking.DataAccess\EventParking.DataAccess.csproj" />
    <ProjectReference Include="..\EventParking.Models\EventParking.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IntegrationTests\" />
    <Folder Include="TestHelpers\" />
    <Folder Include="UnitTests\" />
  </ItemGroup>

</Project>
